#! /bin/bash
COMMONWARN="-g -O3 -Wall -Wextra " # as usual
COMMONWARN+="-pedantic "           # strict standard adherence
COMMONWARN+="-Wshadow "            # local variables that shadow global ones
COMMONWARN+="-Wfloat-equal "       # dont compare floats with == (-> manpage)
COMMONWARN+="-Wundef "             # uninitialized identifier in #if
COMMONWARN+="-Wpointer-arith "     # something depends upon the size of void
COMMONWARN+="-Wcast-align "        # alignment rules violated by cast
COMMONWARN+="-Wcast-qual "         # qualifier removed
COMMONWARN+="-Wstrict-prototypes " # function declared without argument types
COMMONWARN+="-Wstrict-overflow=3 " # avoid optimisations that might overflow
COMMONWARN+="-Wwrite-strings "     # make string literals const char[]
COMMONWARN+="-Wswitch-default "    # switch statement without default case
COMMONWARN+="-Wswitch-enum "       # forgot switch case for one element in enum
COMMONWARN+="-Wconversion "        # warn about implicit conversions
COMMONWARN+="-Winit-self "         # detect more uninitialised values
COMMONWARN+="-ftrapv "             # trap on integer overflow
COMMONWARN+="-Wformat=2 "          # thoroughly check format strings
COMMONWARN+="-Wlogical-op "        # possible misuse of logical operator
COMMONWARN+="-Wredundant-decls "   # multiple decls in same scope
CFLAGS="$COMMONWARN "
#CFLAGS+="-std=c11 "               # no proper support from public includes yet
CFLAGS+="-save-temps "             # leave preproc output to debug macros
CFLAGS+="-Wnested-externs "        # extern within function
export CFLAGS
CCFLAGS="$COMMONWARN -std=c++11 "
CCFLAGS+="-Weffc++ "               # effective C++ code
export CCFLAGS

