#! /bin/bash

filesize() {
    FILESIZE=`ls -l "$1" | awk '{ print $5 }'`
}

if [ "x$1" = "x" ]; then
    echo "Please specify a recording file"
    exit
fi

LASTFILESIZE=0
while [ ! -f $HOME/stop-rec ]; do
    filesize "$1"
    if [ $[$FILESIZE - $LASTFILESIZE] -le 0 ]; then
        for i in $(seq 1 5); do
            play /usr/share/sounds/freedesktop/stereo/dialog-error.oga
        done
        zenity --error --title "Recording" --text 'Stopped recording!'
        exit 1
    fi
    LASTFILESIZE=$FILESIZE
    sleep 5
done

