#! /bin/bash
set -o errexit
set -o nounset

function start_maintenance() {
    zenity \
        --question \
        --title "Upgrade" \
        --text "Perform full system upgrade?" || return
    if type gnome-terminal >/dev/null 2>&1; then
        local terminal="gnome-terminal --"
    else
        local terminal="konsole --nofork -e"
    fi
    $terminal "$HOME/bin/upall"
    zenity --question --title "Upgrade complete" --text "Success?"
}

F_LASTRUN=$HOME/last_maintenance_run
if [[ -f "$F_LASTRUN" ]]; then
    LASTTIME=$(stat -c '%Y' "$F_LASTRUN")
    CURTIME=$(date '+%s')
    INTERVAL=259200 # 3 days
    if [[ $((CURTIME - LASTTIME)) -le $INTERVAL ]]; then
        exit
    fi
fi

start_maintenance

touch "$F_LASTRUN"
