#! /bin/sh
[ "x$1" != "x" -a "x$2" != "x" ] || exit 1
gnuplot <<COMMANDS
set terminal svg size 1920,1080
set output "$2"
set xlabel 'Run Time in Milliseconds'
set ylabel 'Memory Usage (RSS) in KiB'
plot "$1"
quit
COMMANDS
