#! /bin/bash

usage() {
    echo "Usage: rsync-default PORT BWLIMIT ..."
    exit
}

[ "x$1" = "x" ] || [ "x$2" = "x" ] && usage
PORT=$1
[ $PORT -eq 0 ] && PORT=22
BWLIMIT=
[ $2 -gt 0 ] && BWLIMIT="--bwlimit=$2"
shift 2
rsync -av --partial --progress --inplace \
    --rsh="ssh -p $PORT" $BWLIMIT "$@"

