#! /bin/bash

function rsync-dry-cmd() {
>&2 echo "Command: rsync" "${OPTS[@]}" "$@"
>&2 echo
>&2 echo "Result:"
rsync --dry-run "${OPTS[@]}" "$@"
}

OPTS=("-auv" "--partial" "--progress" "--inplace" "--delete")
rsync-dry-cmd "$@"
read -p "Continue? (y/[n])" cont_decision
if [[ $cont_decision != "y" ]]; then
    exit
fi
rsync "${OPTS[@]}" "$@"
