#! /bin/bash
# connect to listening viewer:
#x11vnc -display ":0" -auth /var/run/lxdm/lxdm-\:0.auth -connect remotehost
x11vnc -rfbauth $HOME/.vnc/passwd -localhost -display ":0" -auth /var/lib/gdm/:0.Xauth

