#! /bin/sh

manageservice()
{
    [ -f /var/run/teamviewerd.pid ] && return
    /opt/teamviewer10/tv_bin/teamviewerd -d || return
    while [ -f /tmp/teamviewer-service-required ]; do
        sleep 10
    done
    kill $(cat /var/run/teamviewerd.pid)
}

if [ "$1" = "--manage-service" ]; then
    manageservice
    exit
fi

touch /tmp/teamviewer-service-required
sudo "$0" --manage-service &
while [ ! -f /var/run/teamviewerd.pid ]; do sleep 1; done
/opt/bin/teamviewer10
rm /tmp/teamviewer-service-required

