#! /bin/bash
if which yaourt > /dev/null 2>&1; then
    yaourt -Syua --devel
else
    # Gentoo
    if [ $UID -ne 0 ]; then
        sudo "$0" "$@"
        exit
    else
        emerge --sync
        emerge -DuN --with-bdeps=y "@world" || exit
        emerge --depclean || exit
        while ! revdep-rebuild; do sleep 5; done
        eix-update
    fi
fi
echo
echo
read -p "Consider reading the upgrade messages!"

