#! /bin/bash
function onexit()
{
    echo
    echo
    read -rp "Consider reading the upgrade messages!"
}

function update_arch()
{
    pikaur -Syu --devel
}

function update_flatpak()
{
    flatpak update
}

trap onexit EXIT
update_arch
update_flatpak
