#! /bin/bash

cvlc --sout '#standard' \
    --sout-keep \
    --sout-standard-access http \
    --sout-standard-mux ts \
    --http-port 9090 \
    --no-sout-display-audio \
    --no-sout-display-video \
    "$1"

