#! /bin/bash

usage() {
    echo "Usage: $0 <channel> <audio track> <sub track>"
    echo
    echo "Destination port is 9090"
    echo "Audio and subtitle IDs starting from 0"
    exit 1
}

[ "x$3" = "x" ] && usage
cvlc --sout '#standard' \
    --sout-keep \
    --sout-standard-access http \
    --sout-standard-mux ts \
    --http-port 9090 \
    --no-sout-display-audio \
    --no-sout-display-video \
    --audio-track=$2 \
    --sub-track=$3 \
    "$1" > /tmp/vlc-log 2>&1

