#! /bin/bash

usage() {
    echo "Usage: vlc-record-simple <channel> <dest file>"
    exit
}

[ "x$2" = "x" ] && usage
cvlc --sout '#standard' \
    --sout-standard-access file \
    --sout-standard-mux ts \
    --sout-standard-dst "$2" \
    --no-sout-display-audio \
    --no-sout-display-video \
    "$1" >> /tmp/vlc-log 2>&1

