#! /bin/bash

usage() {
    echo "Usage: vlc-record <channel> <audio track> <sub track> <dest file>"
    echo
    echo "Audio and subtitle IDs starting from 0"
    exit
}

[ "x$4" = "x" ] && usage
cvlc --sout '#standard' \
    --sout-keep \
    --sout-standard-access file \
    --sout-standard-mux ts \
    --sout-standard-dst "$4" \
    --no-sout-display-audio \
    --no-sout-display-video \
    --audio-track=$2 \
    --sub-track=$3 \
    "$1" > /tmp/vlc-log 2>&1

